# Generated by Django 2.1.7 on 2019-02-22 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190218_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_table',
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 1, 45, 32, 586931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 1, 45, 32, 586931, tzinfo=utc)),
        ),
    ]
