# Generated by Django 2.1.7 on 2019-02-22 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190222_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='post',
            name='create_table',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 2, 2, 42, 617553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 2, 2, 42, 617553, tzinfo=utc)),
        ),
    ]
