# Generated by Django 2.1.7 on 2019-02-18 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190218_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_table',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 2, 48, 30, 7019, tzinfo=utc)),
        ),
    ]
